<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDmGjl2E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDmGjl2E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDmGjl2E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDmGjl2E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDmGjl2E\App_KernelDevDebugContainer([
    'container.build_hash' => 'DmGjl2E',
    'container.build_id' => 'd09bd11b',
    'container.build_time' => 1585320636,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDmGjl2E');
